package mazegenerator;/* represents an edge in the tree produced by mazegenerator.MazeGenerator
 * ====================
 * DO NOT EDIT THIS FILE
 * ====================
 * */


import java.util.HashSet;
import java.util.Objects;

class Edge {
    private Pair to;
    private Pair from;


    public Edge(Pair to, Pair from) {
        this.to = to;
        this.from = from;
    }

    public Pair getTo() {
        return to;
    }

    public Pair getFrom() {
        return from;
    }

    public String toString(){
        return from + " -> " + to;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Edge edge = (Edge) o;
        return Objects.equals(to, edge.to) &&
                Objects.equals(from, edge.from);
    }

    @Override
    public int hashCode() {
        return Objects.hash(to, from);
    }


    public static void main(String[] args) {
        // test equality
        HashSet<Edge> edges = new HashSet<>();
        Edge firstEdge = new Edge(new Pair(0,0, 2), new Pair(1,0, 2));
        edges.add(firstEdge);


        Edge secondEdge = new Edge(new Pair(1,0, 2), new Pair(0,0, 2));

        System.out.println(edges.contains(secondEdge) || edges.contains(firstEdge));
    }
}
